chore: refactor staging workflow for improved readability and structure

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -13,48 +13,47 @@ permissions:
 jobs:
   build:
     if: github.ref == 'refs/heads/main'
-    runs-on: 'ubuntu-latest'
+    runs-on: "ubuntu-latest"
     environment: Staging
 
     steps:
-    - name: Check if actor is repository owner
-      run: |
-        if [ "${{ github.actor }}" != "${{ github.repository_owner }}" ]; then
-          echo "This workflow can only be run by the repository owner."
-          exit 1
-        fi
+      - name: Check if actor is repository owner
+        run: |
+          if [ "${{ github.actor }}" != "${{ github.repository_owner }}" ]; then
+            echo "This workflow can only be run by the repository owner."
+            exit 1
+          fi
 
-    - uses: actions/checkout@v4
-      with:
-        ref: main
-        fetch-depth: 0
+      - uses: actions/checkout@v4
+        with:
+          ref: main
+          fetch-depth: 0
 
-    - name: Configure AWS CLI
-      run: |
-        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
+      - name: Configure AWS CLI
+        run: |
+          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
 
-    - name: Check Database Public Accessibility
-      id: check-db
-      run: |
+      - name: Check Database Public Accessibility
+        id: check-db
+        run: |
           DB_INFO=$(aws lightsail get-relational-database --relational-database-name merchtrack-db-sgp1)
           IS_PUBLIC=$(echo "$DB_INFO" | jq -r '.relationalDatabase.publiclyAccessible')
           echo "is_public=$IS_PUBLIC" >> $GITHUB_OUTPUT
 
-
-    - name: Open Database to Public Network
-      if: ${{ steps.check-db.outputs.is_public == 'false' }}
-      run: |
+      - name: Open Database to Public Network
+        if: ${{ steps.check-db.outputs.is_public == 'false' }}
+        run: |
           aws lightsail update-relational-database \
             --relational-database-name merchtrack-db-sgp1 \
             --publicly-accessible
 
-    - name: Wait for Database Availability
-      run: |
+      - name: Wait for Database Availability
+        run: |
           MAX_ATTEMPTS=30
           ATTEMPT=1
-          
+
           while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
             DB_STATUS=$(aws lightsail get-relational-database --relational-database-name merchtrack-db-sgp1 | jq -r '.relationalDatabase.state')
             
@@ -67,109 +66,51 @@ jobs:
             sleep 10
             ATTEMPT=$((ATTEMPT + 1))
           done
-          
+
           if [ $ATTEMPT -gt $MAX_ATTEMPTS ]; then
             echo "Database did not become available within the timeout period"
             exit 1
           fi
 
-    - name: Create env file
-      env:
-        APP_ENV: ${{ secrets.APP_ENV }}
-        NODE_ENV: ${{ secrets.NODE_ENV }}
-        NEXT_PUBLIC_NODE_ENV: ${{ secrets.NEXT_PUBLIC_NODE_ENV }}
-        DATABASE_URL: ${{ secrets.DATABASE_URL }}
-        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
-        NEXT_PUBLIC_DATADOG_APPLICATION_ID: ${{ secrets.NEXT_PUBLIC_DATADOG_APPLICATION_ID }}
-        NEXT_PUBLIC_DATADOG_CLIENT_TOKEN: ${{ secrets.NEXT_PUBLIC_DATADOG_CLIENT_TOKEN }}
-        NEXT_PUBLIC_DATADOG_SITE: ${{ secrets.NEXT_PUBLIC_DATADOG_SITE }}
-        NEXT_PUBLIC_DATADOG_SERVICE_NAME: ${{ secrets.NEXT_PUBLIC_DATADOG_SERVICE_NAME }}
-        NEXT_PUBLIC_CF_BEACON_TOKEN: ${{ secrets.NEXT_PUBLIC_CF_BEACON_TOKEN }}
-        NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
-        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
-        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-        SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}
-        NEXT_RUNTIME: ${{ secrets.NEXT_RUNTIME }}
-        REDIS_HOST: ${{ secrets.REDIS_HOST }}
-        REDIS_PORT: ${{ secrets.REDIS_PORT }}
-        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
-        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
-        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
-        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
-        CLERK_ENCRYPTION_KEY: ${{ secrets.CLERK_ENCRYPTION_KEY }}
-        CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
-        CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
-        CLOUDFLARE_R2_BUCKET_NAME: ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
-        CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
-        CLOUDFLARE_R2_PUBLIC_URL: ${{ secrets.CLOUDFLARE_R2_PUBLIC_URL }}
-        CLOUDFLARE_R2_PUBLIC_DOMAIN: ${{ secrets.CLOUDFLARE_R2_PUBLIC_DOMAIN }}
-        JWT_KEY: ${{ secrets.JWT_KEY }}
-        NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
-        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
-      run: |
-          cat << EOF > .env
-          NEXT_RUNTIME=${NEXT_RUNTIME}
-          APP_ENV=${APP_ENV}
-          NODE_ENV=${NODE_ENV}
-          NEXT_PUBLIC_NODE_ENV=${NEXT_PUBLIC_NODE_ENV}
-          DATABASE_URL=${DATABASE_URL}
-          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
-          NEXT_PUBLIC_DATADOG_APPLICATION_ID=${NEXT_PUBLIC_DATADOG_APPLICATION_ID}
-          NEXT_PUBLIC_DATADOG_CLIENT_TOKEN=${NEXT_PUBLIC_DATADOG_CLIENT_TOKEN}
-          NEXT_PUBLIC_DATADOG_SITE=${NEXT_PUBLIC_DATADOG_SITE}
-          NEXT_PUBLIC_DATADOG_SERVICE_NAME=${NEXT_PUBLIC_DATADOG_SERVICE_NAME}
-          NEXT_PUBLIC_CF_BEACON_TOKEN=${NEXT_PUBLIC_CF_BEACON_TOKEN}
-          NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
-          SENTRY_DSN=${SENTRY_DSN}
-          SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
-          SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE}
-          REDIS_HOST=${REDIS_HOST}
-          REDIS_PORT=${REDIS_PORT}
-          REDIS_PASSWORD=${REDIS_PASSWORD}
-          MAILGUN_API_KEY=${MAILGUN_API_KEY}
-          MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
-          CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
-          CLERK_ENCRYPTION_KEY=${CLERK_ENCRYPTION_KEY}
-          CLOUDFLARE_R2_ACCESS_KEY_ID=${CLOUDFLARE_R2_ACCESS_KEY_ID}
-          CLOUDFLARE_R2_SECRET_ACCESS_KEY=${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
-          CLOUDFLARE_R2_BUCKET_NAME=${CLOUDFLARE_R2_BUCKET_NAME}
-          CLOUDFLARE_R2_ENDPOINT=${CLOUDFLARE_R2_ENDPOINT}
-          CLOUDFLARE_R2_PUBLIC_URL=${CLOUDFLARE_R2_PUBLIC_URL}
-          CLOUDFLARE_R2_PUBLIC_DOMAIN=${CLOUDFLARE_R2_PUBLIC_DOMAIN}
-          JWT_KEY=${JWT_KEY}
-          NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
-          NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
-          EOF
+      - name: Install Doppler CLI
+        uses: dopplerhq/cli-action@v3
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
-      with:
-        registry: https://index.docker.io/v1/
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Setup Doppler Configuration
+        run: |
+          doppler setup --no-prompt --token ${{ secrets.DOPPLER_TOKEN }} --project ${{ secrets.DOPPLER_TARGET_PROJECT }} --config ${{ secrets.DOPPLER_TARGET_CONFIG }}
+          echo "Doppler configuration complete for project ${{ secrets.DOPPLER_TARGET_PROJECT }} with config ${{ secrets.DOPPLER_TARGET_CONFIG }}"
+          doppler secrets download --no-file --format env > .env
+          echo "Secrets downloaded to .env file."
 
-    - name: Build client image and push to Docker Hub
-      uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
-      with:
-        context: .
-        file: ./Dockerfile
-        tags: |
-          gabcat/merchtrack:staging
-        cache-from: |
-          type=registry,ref=gabcat/merchtrack:cache
-          type=registry,ref=gabcat/merchtrack:staging
-        cache-to: type=inline
-        push: true
+      - name: Log in to Docker Hub
+        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
+        with:
+          registry: https://index.docker.io/v1/
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Remove env file
-      if: always()
-      run: |
-        if [ -f .env ]; then
-          rm .env || echo "Warning: Failed to remove .env file"
-        fi
+      - name: Build client image and push to Docker Hub
+        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
+        with:
+          context: .
+          file: ./Dockerfile
+          tags: |
+            gabcat/merchtrack:staging
+          cache-from: |
+            type=registry,ref=gabcat/merchtrack:cache
+            type=registry,ref=gabcat/merchtrack:staging
+          cache-to: type=inline
+          push: true
 
-    - name: Close Database to Public Network
-      run: |
+      - name: Remove env file
+        if: always()
+        run: |
+          if [ -f .env ]; then
+            rm .env || echo "Warning: Failed to remove .env file"
+          fi
+
+      - name: Close Database to Public Network
+        run: |
           aws lightsail update-relational-database \
             --relational-database-name merchtrack-db-sgp1 \
             --no-publicly-accessible
